### ISSUE TITLE
Dates / MODS Xpath used for Date label in IIIF manifest

### ISSUE THREAD

**Issue by mlhale7** [utkdigitalinitiatives/iiif_assemble#33]
@markpbaggett I noticed that we pull in all dates for the "Date" and "Publication date" labels - https://github.com/utkdigitalinitiatives/iiif_assemble/blob/37c4cf2c15d6b9bec190f9a42f1fea3158e8600b/src/IIIF.php#L98. Because we include both human readable dates and edtf dates, the manifests are duplicating content. I'd recommend that we only pull the (not[@edtf] dates (if they exist!) so that we don't duplicate dates. There are instances where we only have one or the other. I noticed this general issue of duplicate date info during the IIIF merge meeting for the Rising from the Ashes collection record.

**Comment by markpbaggett** [comment]
@mlhale7 let's talk about this more.  This may be a small thing that can be worked out quickly, but I want to ensure I understand the ask more clearly.

**Comment by mlhale7** [comment]
Sounds good. Let me know if you'd like me to schedule a meeting or create a ticket.

**Comment by markpbaggett** [comment]
Moving this to Done with [PR-42](https://github.com/utkdigitalinitiatives/iiif_assemble/pull/42).
